#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KANDOU_v1.Resource", IsApplication=true)]

namespace KANDOU_v1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int kanji1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int settings1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int title = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int title1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int vocabulary1 = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int TEXT1 = 2131034134;
			
			// aapt resource value: 0x7f050025
			public const int TEXT1_2 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int TEXT2_2 = 2131034150;
			
			// aapt resource value: 0x7f050000
			public const int back = 2131034112;
			
			// aapt resource value: 0x7f05002f
			public const int back_2 = 2131034159;
			
			// aapt resource value: 0x7f050018
			public const int button1 = 2131034136;
			
			// aapt resource value: 0x7f050027
			public const int button1_2 = 2131034151;
			
			// aapt resource value: 0x7f050019
			public const int button2 = 2131034137;
			
			// aapt resource value: 0x7f050028
			public const int button2_2 = 2131034152;
			
			// aapt resource value: 0x7f05001a
			public const int button3 = 2131034138;
			
			// aapt resource value: 0x7f050029
			public const int button3_2 = 2131034153;
			
			// aapt resource value: 0x7f05001b
			public const int button4 = 2131034139;
			
			// aapt resource value: 0x7f05002a
			public const int button4_2 = 2131034154;
			
			// aapt resource value: 0x7f05001c
			public const int button5 = 2131034140;
			
			// aapt resource value: 0x7f05002b
			public const int button5_2 = 2131034155;
			
			// aapt resource value: 0x7f05001d
			public const int button6 = 2131034141;
			
			// aapt resource value: 0x7f05002c
			public const int button6_2 = 2131034156;
			
			// aapt resource value: 0x7f050013
			public const int buttonGreen = 2131034131;
			
			// aapt resource value: 0x7f050021
			public const int buttonGreen_2 = 2131034145;
			
			// aapt resource value: 0x7f05000c
			public const int buttonNext = 2131034124;
			
			// aapt resource value: 0x7f050038
			public const int buttonNext_2 = 2131034168;
			
			// aapt resource value: 0x7f05000b
			public const int buttonPrevious = 2131034123;
			
			// aapt resource value: 0x7f050036
			public const int buttonPrevious_2 = 2131034166;
			
			// aapt resource value: 0x7f050014
			public const int buttonRed = 2131034132;
			
			// aapt resource value: 0x7f050022
			public const int buttonRed_2 = 2131034146;
			
			// aapt resource value: 0x7f050032
			public const int checkBoxExtended = 2131034162;
			
			// aapt resource value: 0x7f05002e
			public const int deselect_button = 2131034158;
			
			// aapt resource value: 0x7f05000d
			public const int imageView1 = 2131034125;
			
			// aapt resource value: 0x7f050039
			public const int jap_pl_graButton = 2131034169;
			
			// aapt resource value: 0x7f05001e
			public const int kanjiGameButton = 2131034142;
			
			// aapt resource value: 0x7f05000e
			public const int kanji_graButton = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout2 = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout3 = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout4 = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout5 = 2131034135;
			
			// aapt resource value: 0x7f050024
			public const int linearLayout6 = 2131034148;
			
			// aapt resource value: 0x7f050010
			public const int lista_kanjiButton = 2131034128;
			
			// aapt resource value: 0x7f05003b
			public const int lista_slowekButton = 2131034171;
			
			// aapt resource value: 0x7f050011
			public const int lista_zlozen_kanjiButton = 2131034129;
			
			// aapt resource value: 0x7f05003a
			public const int pl_jap_graButton = 2131034170;
			
			// aapt resource value: 0x7f050030
			public const int relativeLayout1 = 2131034160;
			
			// aapt resource value: 0x7f05002d
			public const int save_button = 2131034157;
			
			// aapt resource value: 0x7f050037
			public const int save_button2 = 2131034167;
			
			// aapt resource value: 0x7f050005
			public const int scrollView1 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int scrollView2 = 2131034120;
			
			// aapt resource value: 0x7f050020
			public const int settingsButton = 2131034144;
			
			// aapt resource value: 0x7f05003d
			public const int test_button = 2131034173;
			
			// aapt resource value: 0x7f050003
			public const int textIndex = 2131034115;
			
			// aapt resource value: 0x7f050031
			public const int textIndex_2 = 2131034161;
			
			// aapt resource value: 0x7f050004
			public const int textKanji = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textKanjiMeaning = 2131034118;
			
			// aapt resource value: 0x7f050034
			public const int textKanji_2 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int textMeaning_2 = 2131034165;
			
			// aapt resource value: 0x7f050033
			public const int textReading_2 = 2131034163;
			
			// aapt resource value: 0x7f050009
			public const int textSubmission = 2131034121;
			
			// aapt resource value: 0x7f050015
			public const int textView1 = 2131034133;
			
			// aapt resource value: 0x7f050023
			public const int textView1_2 = 2131034147;
			
			// aapt resource value: 0x7f050007
			public const int textView2 = 2131034119;
			
			// aapt resource value: 0x7f05001f
			public const int wordsGameButton = 2131034143;
			
			// aapt resource value: 0x7f05003c
			public const int wybrane_slowkaButton = 2131034172;
			
			// aapt resource value: 0x7f05000f
			public const int zlozenia_kanji_graButton = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int KanjiInfoLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int KanjiMenuLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainKanjiGameLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenuLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainVocabularyGameLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SettingsVocabularyListLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int VocabularyInfoLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int VocabularyMenuLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int VocabularySelectedInfoLayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int TEXT1 = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
